learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

polls/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
	# url(r'^$', views.index, name='index'),
	# url(r'^(?P<question_id>[0-9]+)/$', views.detail,name='detail'),
	# url(r'^(?P<question_id>[0-9]+)/results/$', views.results,name='results'),
	url(r'^$', views.Indexview.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(),name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(),name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote,name='vote'),
	url(r'^(?P<question_id>[0-9]+)/clearvote/$', views.clearvote,name='clearvote'),
	url(r'^newquestion/$', views.newquestion, name='newquestion'),
	url(r'^addquestion/$', views.addquestion, name='addquestion'),
	url(r'^listquestionnaire/$', views.QuestionnaireView.as_view(), name='listquestionnaire'),
	url(r'^(?P<pk>[0-9]+)/questiondetail/$', views.QuestionnaireDetailView.as_view(), name='questiondetail'),
	url(r'^(?P<questionnaire_id>[0-9]+)/questionnairevote/$', views.questionnairevote,name='questionnairevote'),
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pubdate = models.DateField('date published')

	def was_published_recently(self):
		return self.pubdate>=timezone.now()-datetime.timedelta(days=1)

	def __unicode__(self):
		return self.question_text

class Choice(models.Model):
	question = models.ForeignKey(Question,on_delete = models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice_text

class Questionnaire(models.Model):
	questionnaire_text = models.CharField(max_length=200)
	members = models.ManyToManyField(Question)
	pubdate = models.DateField('date published')

	def was_published_recently(self):
		return self.pubdate>=timezone.now()-datetime.timedelta(days=1)

	def __unicode__(self):
		return self.questionnaire_text

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.views import generic
# from django.template import loader

from .models import Question,Choice,Questionnaire
# Create your views here.


# def index(request):
# 	latest_question_list = Question.objects.order_by('-pubdate')[:5]
# 	# 第一种方法
# 	# template = loader.get_template('polls/index.html')
# 	# context = {'latest_question_list':latest_question_list,}
# 	# return HttpResponse(template.render(context,request))
	
# 	# django的第二种方法
# 	context = {'latest_question_list':latest_question_list,}
# 	return render(request,"polls/index.html", context)


# def detail(request, question_id):
# 	# 第一种方法
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
# 	#django的第二种方法
# 	question = get_object_or_404(Question, pk = question_id)
# 	return render(request, "polls/detail.html", {'question': question})

# def results(request, question_id):
# 	question = get_object_or_404(Question, pk = question_id)
# 	return render(request, "polls/results.html", {'question': question})

class Indexview(generic.ListView):
	"""docstring for Indexview"""
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	def get_queryset(self):
		return Question.objects.all()
		

class DetailView(generic.DetailView):
	"""docstring for DetailView"""
	model = Question
	template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
	"""docstring for DetailView"""
	model = Question
	template_name = 'polls/results.html'


def vote(request, question_id):
	question = get_object_or_404(Question,pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError,Choice.DoesNotExist):
		return render(request, "polls/detail.html", {'question': question,'error_message':"you did't select a choice."})
	else:
		selected_choice.votes += 1
		selected_choice.save()
	return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))


def clearvote(request, question_id):
	question = get_object_or_404(Question,pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError,Choice.DoesNotExist):
		selected_choices = question.choice_set.all()
		for selected_choice in selected_choices:
			selected_choice.votes = 0
			selected_choice.save()
	else:
		selected_choice.votes = 0
		selected_choice.save()

	return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

def newquestion(request):
	"""docstring for DetailView"""
	return render(request, "polls/newquestion.html", {})

def addquestion(request):
	if request.method == 'POST':
		addquestion=request.POST.get("question",None)
		currenttime=request.POST.get("currenttime",None)
		choicevalues = request.POST.getlist("choicevalues",None)
		if addquestion!=None and currenttime!=None:
			newquestion = Question()
			newquestion.question_text = addquestion
			newquestion.pubdate = currenttime
			newquestion.save()
			A = Question.objects.get(question_text=newquestion)
			for choicevalue in choicevalues:
				choices = Choice()
				choices.question=A
				choices.choice_text = choicevalue
				choices.votes = 0
				choices.save()

		return HttpResponseRedirect(reverse('polls:index',args=()))
	return HttpResponseRedirect(reverse('polls:newquestion',args=()))


class QuestionnaireView(generic.ListView):
	template_name = 'polls/listquestionnaire.html'
	context_object_name = "questionnaire_list"
	def get_queryset(self):
		return Questionnaire.objects.all()


class QuestionnaireDetailView(generic.DetailView):
	"""docstring for DetailView"""
	model = Questionnaire
	template_name = 'polls/questiondetail.html'


def questionnairevote(request, questionnaire_id):
	questionnaire = get_object_or_404(Questionnaire,pk=questionnaire_id)
	#print questionnaire.id
	for question in questionnaire.members.all():
		try:
			selected_choice = question.choice_set.get(pk=request.POST.get('choice'))
			print str(request.POST.get('choice'))
		except (KeyError,Choice.DoesNotExist):
			return render(request, "polls/questiondetail.html", {'questionnaire': questionnaire,'error_message':"you did't select a choice."})
		else:
			selected_choice.votes += 1
			selected_choice.save()
	return HttpResponseRedirect(reverse('polls:index',args=()))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>question_detail</title>
    </head>

	<body>
		<a href="{% url 'polls:index'%}">Home</a>
		<h1>question_{{question.pk}} : </h1>
		<h2>{{question.question_text}}</h2>
		{% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}

		<form action="{% url 'polls:vote' question.id %}" method="post">
			{% csrf_token %}
			{% for choice in question.choice_set.all%}
				<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
				<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
			{% endfor %}
			<input type="submit" name="Vote">
		</form>

	</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>question_list</title>
        <style type="text/css">

        input {
        	margin:0 px;padding:0;
        }
		ol {
		margin:0 px;padding:0;
		}
		</style>

    </head>

	<body>
		<h1> 问卷调查 </h1>
		<a href="{% url 'polls:newquestion'%}">新建问题</a>
		<a href="{% url 'polls:index'%}">管理问题</a>
		<a href="{% url 'polls:listquestionnaire'%}">问卷列表</a>
		{% if latest_question_list %}
		    <ul >
		    {% for question in latest_question_list %}
		    	<ol>
		    	<input type="checkbox" name="question_select" value="{{question.id}}" />
		    	<a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></ol>
				<ol type="A" style="padding-left : 30px">
					{% for choice in question.choice_set.all%}
						<li><label for="choice{{forloop.counter}}">{{choice.choice_text}}........{{choice.votes}}</label><br/></li>
					{% endfor %}
				</ol>
		    {% endfor %}
		    </ul>
		{% else %}
		    <p>No polls are available.</p>
		{% endif %}
	</body>
</html>

polls/templates/polls/listquestionnaire.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>question_detail</title>	
    </head>

	<body>
		<h1> 问卷 </h1>
		<a href="{% url 'polls:index'%}">Home</a>
		{% if questionnaire_list %}
		    <ul >
		    {% for questionnaire in questionnaire_list %}
		    	<a href="{% url 'polls:questiondetail' questionnaire.id %}">{{questionnaire.id}}.{{questionnaire}}</a></ol>
<!-- 			{%for quuq in questionnaire.members.all%}  
		    	{{quuq}}
		    	{%endfor%} -->
		    {% endfor %}
			</ul>
		{% else %}
		    <p>No polls are available.</p>
		{% endif %}
	</body>
</html>

polls/templates/polls/newquestion.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>question_detail</title>	
        <meta name="save" content="history">  
		<style type="text/css">  
			input{behavior:url(#default#savehistory)};  
		</style> 
    </head>

	<body>

		<fieldset>
			<legend>
				新建问题
			</legend>

			<div>
				<form action="{% url 'polls:addquestion' %}" method="post" onsubmit="return check()" >
					{% csrf_token %}
				 	question: <input type="text"  id="question" name="question" onchange="checkquestion()"/><span id="checktext1"></span>
				 	time: <input type="date"  id="currenttime" name="currenttime" onchange="checkdate()"/><span id="checktext2"></span>
				 	<div id="div">
				 		<input type="button"  value="增加选项" onclick="addText()"/><span id="checktext3"></span>
	        			<div>选项1:<input type='text' name = 'choicevalues'> <input type='button' value='删除' onclick='deleteText(this)'></div>
	    			</div>
				 	<input type="submit" value="提交" />
				</form>
			</div>
		</fieldset>

		<script type="text/javascript">
			var num = 2
		    function addText(){
		        var div = document.getElementById("div");
		        div.innerHTML += "<div>选项"+ num +":<input type='text' name = 'choicevalues' onchange='checkchoice()'/> <input type='button' value='删除' onclick='deleteText(this)'></div>";
		        num ++;
		    }
		    function deleteText(This){
		        //获取删除按钮的父元素 的 父元素 利用 爷爷元素 删除
		        This.parentNode.parentNode.removeChild(This.parentNode);
		    }
		</script>



		<script type="text/javascript">

			function checkquestion() {
				var check = false;
				var question = document.getElementById("question").value;
				if (question.length <= 0) {
					document.getElementById("checktext1").innerHTML = "  × 不能为空";
					check = false;
				}else if(question.length >200) 
				{
					document.getElementById("checktext1").innerHTML = "  × 不要多于10位";
					check = false;
				}
				else {
					document.getElementById("checktext1").innerHTML = "  √";
					check = true;
				}
				return check;
			}

			function checkdate() {
				var check = false;
				var currenttime = document.getElementById("currenttime").value;
				if (currenttime.length <= 0) {
					document.getElementById("checktext2").innerHTML = "  × 不能为空";
					check = false;
				} else {
					document.getElementById("checktext2").innerHTML = "  √";
					check = true;
				}
				return check;
			}

			function check() {
				var check =  checkquestion() && checkdate();
				return check;
			 
			}

		</script>

	</body>
</html>






polls/templates/polls/questiondetail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>question_detail</title>	
    </head>

	<body>
		<h1> 问卷{{questionnaire.pk}} -- {{questionnaire.questionnaire_text}}</h1>
		<a href="{% url 'polls:index'%}">Home</a><br/>
		{% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}

			{%for question in questionnaire.members.all%}  
		    	<form action="{% url 'polls:questionnairevote' questionnaire.id %}" method="post">
		    	{{question.id}}.{{question}}<br/>
				{% csrf_token %}
		    	{% for choice in question.choice_set.all%}
					<input type="checkbox" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
					<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
				{% endfor %} 
				<input type="submit" name="Vote"></form>
			{%endfor%}
			
	</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>question_list</title>
        <style type="text/css">
        	p {
        		margin: 10 px;
        		padding: 10 px;
        	}
        </style>
    </head>

	<body>
		<h1>{{ question.question_text }}</h1>

		<ul style="padding:0">
		{% for choice in question.choice_set.all %}
		    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes.pluralize }}</li>
		{% endfor %}
		</ul>

		<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
		<a href="{% url 'polls:index'%}">Home</a>
		<div style="text-align:center;">
		<h1>投票管理</h1>
		<form action="{% url 'polls:clearvote' question.id %}" method="post">
			{% csrf_token %}
			{% for choice in question.choice_set.all%}
				<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
				<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
			{% endfor %}
			<input type="submit" name="Vote" value="清空投票">
		</form></div>
	</body>
</html>